language: csharp
solution: KeesTalksTech-Utility-Pack/KeesTalksTech.UtilityPack.sln
before_install:
  - mkdir -p .nuget
  - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - mono .nuget/nuget.exe # Output NuGet's version number
install:
  - mono .nuget/nuget.exe restore KeesTalksTech-Utility-Pack/KeesTalksTech.UtilityPack.sln -Verbosity detailed
  - mono .nuget/nuget.exe install NUnit.Runners -Version 3.2.1
script:
  - xbuild /p:Configuration=Release KeesTalksTech-Utility-Pack/KeesTalksTech.UtilityPack.sln
  - mono ./testrunner/NUnit.Runners.3.2.1/tools/nunit-console.exe ./KeesTalksTech-Utility-Pack/KeesTalksTech.Utilities.Tests/bin/Release/KeesTalksTech.Utilities.Tests.dll